### ISSUE TITLE
Pass arguments to go list

### ISSUE THREAD

**Issue by jonesaaronj** [axw/gocov#82]
It would be nice if when test.go calls go list -e it could be passed additional parameters.  If you are using modules and building in say a docker environment gocov will fail when it cannot reach an external git repo.  If list respected the -m flag it should just use the vendor directory instead.

**Comment by junedev** [comment]
I think I have the same issue. `gocov test -mod=vendor ./...` should not install dependencies but use the vendor folder instead. That does not work, dependencies are installed, probably because `go list` does not get the arguments as @jonesaaronj explained.

**Comment by axw** [comment]
@jonesaaronj I'm sorry for not responding sooner, notifications were somehow disabled for me and I simply was not aware of this issue.

If you're still in need of this change, please feel free to send a PR and I'd be happy to review it. Otherwise, setting `GOFLAGS` seems like a reasonable workaround to me.

**Comment by junedev** [comment]
@axw @jonesaaronj As far as modules are concerned this issue was solved by the Go team. In Go 1.14 or higher all go commands default to respecting the vendor folder if there is one. See https://golang.org/doc/go1.14#go-command .
We were able to remove the GOFLAGS setting now as part of our Go update and it works just fine.

**Comment by axw** [comment]
Good point, thanks @junedev!

I'll close this, happy to revisit if there's a still need.
